Feat/tela registerprofessional
ExodiaTeam/connectdeaf-mobile pull request #16
Opened 2024-12-13 17:22 UTC by Vitorloula

Tela Register Professional
![Captura de tela 2024-12-13 142104](https://github.com/user-attachments/assets/bd512caa-05ab-4dd1-ac03-a50e5d404814)

2024-12-13 19:13 UTC, kairosb requested changes
Existe um componente que já está sendo usado como dropdown, adicionando essa opção de dropdown no componente de Input esta trazendo redundância.

2024-12-13 19:16 UTC, kairosb reviewed
Na tela RegisterScreen foi removido o componente HeaderSection e depois você só importou ele mas não está sendo usado

2024-12-13 19:17 UTC, kairosb reviewed
Mantenha coerência entre o nome do arquivo e o nome da função 

![image](https://github.com/user-attachments/assets/0348324c-9ef3-4f00-8759-c8a0ecefef4b)

2024-12-19 20:32 UTC, Vitorloula commented
Conflitos nas telas de Serviço e Registro, ressolvidos

2025-01-08 17:26 UTC, kairosb approved these changes

2025-01-09 00:21 UTC, merged